name = "Simple Modpack"
author = "quaoz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99e3720602532a037ae09554acbe93de0f1515cdf090fac1ebb5f00888439cf5"

[versions]
minecraft = "1.20"
quilt = "0.19.2-beta.2"
