name = "Simple Modpack"
author = "quaoz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c292d15509255568ff5a674e25801aa6ad99719576c27847e4be83d464156b42"

[versions]
fabric = "0.14.21"
minecraft = "1.20"
