name = "Simple Modpack"
author = "quaoz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79da06c8ede774a362e08ed771eb736a614180150adb2e771e38e9493ffe9160"

[versions]
fabric = "0.14.21"
minecraft = "1.20"
