name = "Simple Modpack"
author = "quaoz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "960ea812dc1ce3bad1653646eed758892b06eec933e1bf19290e64eaed84e9c2"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2-beta.2"
