name = "xenia"
author = "xenia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61174028383d17c86f2bd4d5a37f49c6896a776212f5bc3917a94df87fdcf044"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.60"
