name = "Simple Modpack"
author = "quaoz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54fd82f7891584a9c37ded3169d26823a712da856fb24212aa717df28ebfebd4"

[versions]
minecraft = "1.20"
quilt = "0.19.0-beta.18"
