name = "xenia"
author = "xenia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b92a5bf2da03045f36a6327f1a060e6bd1cd44aabd2d60e1938e5edbdcd0ac60"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.60"
