name = "Simple Modpack"
author = "quaoz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce63bb8bfac9e20812fa247bb51cdf6b524769778e9f421b412aad818859435a"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
